### ISSUE TITLE
Portuguese (Brazil) language isn't detected

### ISSUE THREAD

**Issue by danimesq** [HelloZeroNet/zeronet.io#22]
My browser isn't detecting it automatically, only the portuguese of Portugal.

**Comment by HelloZeroNet** [comment]
please paste your "Accept language" line from http://www.reliply.org/tools/requestheaders.php

**Comment by danimesq** [comment]
`pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4`

**Comment by HelloZeroNet** [comment]
It should work now, please test

**Comment by danimesq** [comment]
Now its working, thanks.
But, why I can't see any commit here about it?

**Comment by anoadragon453** [comment]
@Plasmmer language detection may be outside the scope of this repo.

@HelloZeroNet I believe this issue can now be closed.
