### ISSUE TITLE
'Download Android package' link nearly impossible to click

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/zeronet.io#28]
Something up with the way Android handles links. It's possible after tapping the link 5-7 times, but most users will think the button is broken before then.

Would help with lowering the barrier to adoption :)

**Comment by anoadragon453** [comment]
According to [this blog post](https://css-tricks.com/annoying-mobile-double-tap-link-issue/) it may have to do with the `:hover` CSS attribute of the button preventing the link from being clicked later.

I also notice the same inability to press the "Confirm to change this site's max size to 20MB" ZeroNet notification on Android. The button is highlighted, but can almost never be actually clicked after that.

**Comment by HelloZeroNet** [comment]
I have no Android phone, but I tried to reproduce it with browserstack.com emulator without any success. What Android version / browser are you using?

**Comment by anoadragon453** [comment]
I'm using android 8.1 with a Nexus 6P. It was reproducible with a
friend's Galaxy S6 as well.

I assume it does, but does BrowserStack reproduce Android's
functionality where one tap is a hover, then a click?

**Comment by anoadragon453** [comment]
Interesting, so this problem only seems to occur in Firefox for Android. In Chrome it works fine. I am using the latest Firefox version 57.0.1.

**Comment by MuxZeroNet** [comment]
> I have no Android phone

You don't need to.

To emulate mobile rendering, use the _Responsive Design Mode_ in Firefox.

**Comment by HelloZeroNet** [comment]
I was able to reproduce it in Firefox and find the problem: for some reasons Firefox does not respected `pointer-events: none` on the hidden  language menu. Added `max-height: 0px`, works for me in the responsive design mode. Please confirm if it's fixed on mobile.

**Comment by anoadragon453** [comment]
Yes, I can confirm this is now fixed!

My only concern is now that I still cannot click on notification banners on ZeroHello (or any other ZeroNet site using ZeroNet notifications) on mobile Firefox, while I can on Chrome. This leads me to believe that it is the same issue, however I will now close this issue and create a new one on the main repo.
