### ISSUE TITLE
Replace first instance of 'Bitcoin' with something else

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/zeronet.io#30]
Twice now I've come across threads where someone posts a link to ZeroNet, which everyone gets excited about until they notice the word 'Bitcoin' at the top of the site and immediately shrug it off as requiring a Blockchain.

Example 1: https://reddit.com/comments/7t9t1g/comment/dtbd4pn
Example 2: https://www.reddit.com/r/linux/comments/7juju3/zeronet_an_interesting_decentralized_p2p_network/

**We need to change this.**

The first mention of Bitcoin puts people off. The second one about no passwords is less daunting. I propose we change the line from:

"Open, free and uncensorable websites,
using Bitcoin cryptography and BitTorrent network"

to

"Open, free and uncensorable websites,
using **strong** cryptography and **the** BitTorrent network"

Substitute other words in as you like, but I suggest not changing it too much as updating translations would be a hassle. With the above change "Bitcoin" simply needs to be changed to that language's equivalent of "strong", which shouldn't be too bad.

I think this minute change would really help make the appearance of Zeronet better in the respective tech circles whom will be a large part of ZeroNet's initial niche audience, and will be the ones to initially shape and let it grow.

**Comment by purplesyringa** [comment]
"Crypto" was replaced with "cryptography" already, can this be closed? @HelloZeroNet

**Comment by HelloZeroNet** [comment]
I also updated the title: https://github.com/HelloZeroNet/zeronet.io/commit/e9d5c9e68489639a2ca3b87d74b01e798d4f3d43
