### ISSUE TITLE
Website should list Tamas's OpenPGP pubkey

### ISSUE THREAD

**Issue by JeremyRand** [HelloZeroNet/zeronet.io#44]
It would be useful for the ZeroNet website to list @HelloZeroNet's OpenPGP pubkey.  This would help users triangulate to make sure they have the correct key, in case the user's connection to GitHub is compromised.

Including both the full key (as a `.asc` file) and the 160-bit fingerprint would be ideal, since the fingerprint by itself is subject to censorship by keyservers (and also the fingerprint is based on SHA1, which is insecure), but the fingerprint is useful to triangulate via keyservers if the keyservers are available.

**Comment by HelloZeroNet** [comment]
Thanks for the suggestion I have added my pubkey: https://github.com/HelloZeroNet/zeronet.io/commit/c9eb0b475920fd004b849f09e804d6db1994f9f7
