### ISSUE TITLE
Twitter account metadata points to non-TLS URL

### ISSUE THREAD

**Issue by JeremyRand** [HelloZeroNet/zeronet.io#45]
The Twitter account metadata for https://www.twitter.com/HelloZeroNet points to `http://zeronet.io`, which has TLS disabled. Please replace it with an HTTPS URL.

(This seems like the best repo to report this issue in, sorry if it's off-topic, I couldn't find a more on-topic repo.)

**Comment by HelloZeroNet** [comment]
Thanks, fixed, I also corrected it on reddit.
