### ISSUE TITLE
RTL problem in Persian translation.

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/zeronet.io#48]
The Persian language display should be from right-to-left, but in [zeronet.io](https://zeronet.io/fa) by default, all translations are displayed left-to-right.
To solve this problem, you can add `dir="rtl"` or something like that to paragraphs.

![image](https://user-images.githubusercontent.com/43755665/88539461-8a8c3300-d026-11ea-9afa-a019ee87a5fd.png)

**Comment by HelloZeroNet** [comment]
I'm not sure if it's right this way, but I have added some modification: https://zeronet.io/fa

https://github.com/HelloZeroNet/zeronet.io/commit/69193a2ee0ada56db9f4e98e9aa7a6a177a4cb5a

**Comment by ghost** [comment]
> I'm not sure if it's right this way, but I have added some modification: https://zeronet.io/fa
> 
> [69193a2](https://github.com/HelloZeroNet/zeronet.io/commit/69193a2ee0ada56db9f4e98e9aa7a6a177a4cb5a)

that's right, thanks.
